services:

  mealplans-db:
    image: postgres:15-alpine
    container_name: mealplans-db
    environment:
      POSTGRES_DB: sgppln
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5444:5432"
    volumes:
      - mealplans_db_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - mealplans-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  mealplans-api:
    build: .
    container_name: mealplans-api
    environment:
      DATASOURCE_URL: jdbc:postgresql://mealplans-db:5432/sgppln
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: admin
      LOKI_URL: http://loki:3100
    ports:
      - "8081:8081"
    depends_on:
      mealplans-db:
        condition: service_healthy
    networks:
      - mealplans-network
    restart: unless-stopped

  loki:
    image: grafana/loki:3.3.2
    container_name: grupo3-loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./monitoring/loki/loki-config.yml:/etc/loki/local-config.yaml
      - loki_data:/loki
    ports:
      - "3100:3100"
    networks:
      - mealplans-network

  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: grupo3-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - mealplans-network

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grupo3-grafana
    depends_on:
      - prometheus
      - loki
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - mealplans-network

volumes:
  mealplans_db_data:
  loki_data:
  prometheus_data:
  grafana_data:

networks:
  mealplans-network:
    driver: bridge
