spring.application.name=nurtricenter-mealplans


spring.datasource.url=jdbc:postgresql://localhost:5432/sgppln
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=update

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.error.whitelabel.enabled=true