spring.application.name=mealplans

spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://localhost:5432/sgppln}
spring.datasource.username=${DATASOURCE_USERNAME:postgres}
spring.datasource.password=${DATASOURCE_PASSWORD:admin}
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=update

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.error.whitelabel.enabled=true