#------------------ APP CONFIG --------------------#
spring.application.name=mealplans

#------------------SERVER CONFIG-------------------#
#------------------service base--------------------#
server.port=8081
#------------------service pool thread-------------#
spring.thread-pool.queue-size=2250
spring.thread-pool.max-threads=50
spring.thread-pool.core-threads=10

#------------------DOCUMENTATION CONFIG-------------#
#------------------swagger config-------------------#
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger.path-location=/
#springdoc.swagger.path-location=/str-entorno-back/
springdoc.swagger-ui.configUrl=${springdoc.swagger.path-location}v3/api-docs/swagger-config
springdoc.swagger-ui.url=${springdoc.swagger.path-location}v3/api-docs
springdoc.swagger-ui.path=/apidoc/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true

#------------------DATABASE CONFIG------------------#
#------------------database connection info---------#
spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://localhost:5432/sgppln}
spring.datasource.username=${DATASOURCE_USERNAME:postgres}
spring.datasource.password=${DATASOURCE_PASSWORD:admin}
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=update

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.error.whitelabel.enabled=true