#!/usr/bin/env bash
echo "Ejecutando validaciones pre-commit..."
mvn clean test spotless:check
if [ $? -ne 0 ]; then
    echo "❌ Las validaciones fallaron. Revisa los errores."
    exit 1
fi
echo "✅ Validaciones exitosas."
exit 0
