global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mealplans-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mealplans-api:8081']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'mealplans-api'
